// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: pkg/subscriber/proto/subscriber.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SubscriberService_AddRoomSubscriber_FullMethodName    = "/proto.SubscriberService/AddRoomSubscriber"
	SubscriberService_RemoveRoomSubscriber_FullMethodName = "/proto.SubscriberService/RemoveRoomSubscriber"
)

// SubscriberServiceClient is the client API for SubscriberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriberServiceClient interface {
	AddRoomSubscriber(ctx context.Context, in *AddRoomSubscriberRequest, opts ...grpc.CallOption) (*AddRoomSubscriberResponse, error)
	RemoveRoomSubscriber(ctx context.Context, in *RemoveRoomSubscriberRequest, opts ...grpc.CallOption) (*RemoveRoomSubscriberResponse, error)
}

type subscriberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriberServiceClient(cc grpc.ClientConnInterface) SubscriberServiceClient {
	return &subscriberServiceClient{cc}
}

func (c *subscriberServiceClient) AddRoomSubscriber(ctx context.Context, in *AddRoomSubscriberRequest, opts ...grpc.CallOption) (*AddRoomSubscriberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRoomSubscriberResponse)
	err := c.cc.Invoke(ctx, SubscriberService_AddRoomSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriberServiceClient) RemoveRoomSubscriber(ctx context.Context, in *RemoveRoomSubscriberRequest, opts ...grpc.CallOption) (*RemoveRoomSubscriberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRoomSubscriberResponse)
	err := c.cc.Invoke(ctx, SubscriberService_RemoveRoomSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriberServiceServer is the server API for SubscriberService service.
// All implementations must embed UnimplementedSubscriberServiceServer
// for forward compatibility
type SubscriberServiceServer interface {
	AddRoomSubscriber(context.Context, *AddRoomSubscriberRequest) (*AddRoomSubscriberResponse, error)
	RemoveRoomSubscriber(context.Context, *RemoveRoomSubscriberRequest) (*RemoveRoomSubscriberResponse, error)
	mustEmbedUnimplementedSubscriberServiceServer()
}

// UnimplementedSubscriberServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriberServiceServer struct {
}

func (UnimplementedSubscriberServiceServer) AddRoomSubscriber(context.Context, *AddRoomSubscriberRequest) (*AddRoomSubscriberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoomSubscriber not implemented")
}
func (UnimplementedSubscriberServiceServer) RemoveRoomSubscriber(context.Context, *RemoveRoomSubscriberRequest) (*RemoveRoomSubscriberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRoomSubscriber not implemented")
}
func (UnimplementedSubscriberServiceServer) mustEmbedUnimplementedSubscriberServiceServer() {}

// UnsafeSubscriberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriberServiceServer will
// result in compilation errors.
type UnsafeSubscriberServiceServer interface {
	mustEmbedUnimplementedSubscriberServiceServer()
}

func RegisterSubscriberServiceServer(s grpc.ServiceRegistrar, srv SubscriberServiceServer) {
	s.RegisterService(&SubscriberService_ServiceDesc, srv)
}

func _SubscriberService_AddRoomSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoomSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberServiceServer).AddRoomSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriberService_AddRoomSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberServiceServer).AddRoomSubscriber(ctx, req.(*AddRoomSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriberService_RemoveRoomSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoomSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberServiceServer).RemoveRoomSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriberService_RemoveRoomSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberServiceServer).RemoveRoomSubscriber(ctx, req.(*RemoveRoomSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriberService_ServiceDesc is the grpc.ServiceDesc for SubscriberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SubscriberService",
	HandlerType: (*SubscriberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRoomSubscriber",
			Handler:    _SubscriberService_AddRoomSubscriber_Handler,
		},
		{
			MethodName: "RemoveRoomSubscriber",
			Handler:    _SubscriberService_RemoveRoomSubscriber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/subscriber/proto/subscriber.proto",
}
