// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: pkg/subscriber/proto/subscriber.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRoomSubscriberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     uint64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Subscriber string `protobuf:"bytes,3,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
}

func (x *AddRoomSubscriberRequest) Reset() {
	*x = AddRoomSubscriberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_subscriber_proto_subscriber_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomSubscriberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomSubscriberRequest) ProtoMessage() {}

func (x *AddRoomSubscriberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_subscriber_proto_subscriber_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomSubscriberRequest.ProtoReflect.Descriptor instead.
func (*AddRoomSubscriberRequest) Descriptor() ([]byte, []int) {
	return file_pkg_subscriber_proto_subscriber_proto_rawDescGZIP(), []int{0}
}

func (x *AddRoomSubscriberRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *AddRoomSubscriberRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddRoomSubscriberRequest) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

type AddRoomSubscriberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddRoomSubscriberResponse) Reset() {
	*x = AddRoomSubscriberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_subscriber_proto_subscriber_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomSubscriberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomSubscriberResponse) ProtoMessage() {}

func (x *AddRoomSubscriberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_subscriber_proto_subscriber_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomSubscriberResponse.ProtoReflect.Descriptor instead.
func (*AddRoomSubscriberResponse) Descriptor() ([]byte, []int) {
	return file_pkg_subscriber_proto_subscriber_proto_rawDescGZIP(), []int{1}
}

type RemoveRoomSubscriberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   uint64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *RemoveRoomSubscriberRequest) Reset() {
	*x = RemoveRoomSubscriberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_subscriber_proto_subscriber_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRoomSubscriberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomSubscriberRequest) ProtoMessage() {}

func (x *RemoveRoomSubscriberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_subscriber_proto_subscriber_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomSubscriberRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoomSubscriberRequest) Descriptor() ([]byte, []int) {
	return file_pkg_subscriber_proto_subscriber_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveRoomSubscriberRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RemoveRoomSubscriberRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RemoveRoomSubscriberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveRoomSubscriberResponse) Reset() {
	*x = RemoveRoomSubscriberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_subscriber_proto_subscriber_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRoomSubscriberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomSubscriberResponse) ProtoMessage() {}

func (x *RemoveRoomSubscriberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_subscriber_proto_subscriber_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomSubscriberResponse.ProtoReflect.Descriptor instead.
func (*RemoveRoomSubscriberResponse) Descriptor() ([]byte, []int) {
	return file_pkg_subscriber_proto_subscriber_proto_rawDescGZIP(), []int{3}
}

var File_pkg_subscriber_proto_subscriber_proto protoreflect.FileDescriptor

var file_pkg_subscriber_proto_subscriber_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f,
	0x0a, 0x18, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x22,
	0x1b, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x52, 0x0a, 0x1b,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xd0, 0x01, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f,
	0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x61, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_subscriber_proto_subscriber_proto_rawDescOnce sync.Once
	file_pkg_subscriber_proto_subscriber_proto_rawDescData = file_pkg_subscriber_proto_subscriber_proto_rawDesc
)

func file_pkg_subscriber_proto_subscriber_proto_rawDescGZIP() []byte {
	file_pkg_subscriber_proto_subscriber_proto_rawDescOnce.Do(func() {
		file_pkg_subscriber_proto_subscriber_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_subscriber_proto_subscriber_proto_rawDescData)
	})
	return file_pkg_subscriber_proto_subscriber_proto_rawDescData
}

var file_pkg_subscriber_proto_subscriber_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_subscriber_proto_subscriber_proto_goTypes = []interface{}{
	(*AddRoomSubscriberRequest)(nil),     // 0: proto.AddRoomSubscriberRequest
	(*AddRoomSubscriberResponse)(nil),    // 1: proto.AddRoomSubscriberResponse
	(*RemoveRoomSubscriberRequest)(nil),  // 2: proto.RemoveRoomSubscriberRequest
	(*RemoveRoomSubscriberResponse)(nil), // 3: proto.RemoveRoomSubscriberResponse
}
var file_pkg_subscriber_proto_subscriber_proto_depIdxs = []int32{
	0, // 0: proto.SubscriberService.AddRoomSubscriber:input_type -> proto.AddRoomSubscriberRequest
	2, // 1: proto.SubscriberService.RemoveRoomSubscriber:input_type -> proto.RemoveRoomSubscriberRequest
	1, // 2: proto.SubscriberService.AddRoomSubscriber:output_type -> proto.AddRoomSubscriberResponse
	3, // 3: proto.SubscriberService.RemoveRoomSubscriber:output_type -> proto.RemoveRoomSubscriberResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_subscriber_proto_subscriber_proto_init() }
func file_pkg_subscriber_proto_subscriber_proto_init() {
	if File_pkg_subscriber_proto_subscriber_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_subscriber_proto_subscriber_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomSubscriberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_subscriber_proto_subscriber_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomSubscriberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_subscriber_proto_subscriber_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRoomSubscriberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_subscriber_proto_subscriber_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRoomSubscriberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_subscriber_proto_subscriber_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_subscriber_proto_subscriber_proto_goTypes,
		DependencyIndexes: file_pkg_subscriber_proto_subscriber_proto_depIdxs,
		MessageInfos:      file_pkg_subscriber_proto_subscriber_proto_msgTypes,
	}.Build()
	File_pkg_subscriber_proto_subscriber_proto = out.File
	file_pkg_subscriber_proto_subscriber_proto_rawDesc = nil
	file_pkg_subscriber_proto_subscriber_proto_goTypes = nil
	file_pkg_subscriber_proto_subscriber_proto_depIdxs = nil
}
