// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/omran95/chat-app/pkg/common"
	"github.com/omran95/chat-app/pkg/config"
	"github.com/omran95/chat-app/pkg/room"
)

// Injectors from wire.go:

func InitializeRoomServer(name string) (*common.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	httpLog, err := common.NewHttpLog(configConfig)
	if err != nil {
		return nil, err
	}
	engine := room.NewGinEngine(httpLog, configConfig)
	melodyConn := room.NewWebSocketConnection()
	idGenerator, err := common.NewSonyFlake()
	if err != nil {
		return nil, err
	}
	roomServiceImpl := room.NewRoomService(idGenerator)
	httpServer := room.NewHttpServer(name, httpLog, engine, melodyConn, configConfig, roomServiceImpl)
	router := room.NewRouter(httpServer)
	server := common.NewServer(name, router)
	return server, nil
}
