global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'room_monitor'
    static_configs:
      - targets: ['deployments-chat-room-1:8080','deployments-chat-room-2:8080','deployments-chat-room-3:8080']
  - job_name: 'subscriber_monitor'
    static_configs:
      - targets: ['deployments-subscriber-1:8080', 'deployments-subscriber-2:8080', 'deployments-subscriber-3:8080']
